#!/usr/bin/python
import sys

previous_HEAD_ref = sys.argv[1]
new_HEAD_ref = sys.argv[2]
is_branch_checkout = sys.argv[3]

print("Elad's checkout git hook")
print("previous_HEAD_ref =  %s" % previous_HEAD_ref)
print("new_HEAD_ref =       %s" % new_HEAD_ref)
print("is_branch_checkout = %s" % is_branch_checkout)

